using ArandanoIRT_Backend.Application.Interfaces.Auditing;
using ArandanoIRT_Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.Extensions.Logging;

namespace ArandanoIRT_Backend.Infrastructure.Persistence.Auditing
{
    /// <summary>
    /// Implements <see cref="IAuditEntryGenerator"/> to create audit trail entries
    /// in the <c>Auditsystemtable</c> for changes made to specific "system" or related data entities
    /// like <c>Plantstatehistory</c> and <c>Plantobservation</c>.
    /// </summary>
    public class AuditSystemTableGenerator : IAuditEntryGenerator
    {
        private readonly IAuditHelperService _auditHelper;
        private readonly ILogger<AuditSystemTableGenerator> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditSystemTableGenerator"/> class.
        /// </summary>
        /// <param name="auditHelper">The helper service for common auditing tasks.</param>
        /// <param name="logger">The logger for recording information and warnings.</param>
        /// <exception cref="ArgumentNullException">Thrown if auditHelper or logger is null.</exception>
        public AuditSystemTableGenerator(IAuditHelperService auditHelper, ILogger<AuditSystemTableGenerator> logger)
        {
            _auditHelper = auditHelper ?? throw new ArgumentNullException(nameof(auditHelper));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <inheritdoc/>
        /// <remarks>
        /// This generator handles only the specified entity types:
        /// <c>Plantstatehistory</c> and <c>Plantobservation</c>.
        /// It explicitly does NOT handle Status, TableRelation, FailedLoginAttempt, DeviceLog, etc.
        /// </remarks>
        public bool CanHandle(EntityEntry entry)
        {
            // Handles only the specified entity types.
            return entry.Entity is Plantstatehistory ||
                   entry.Entity is Plantobservation;
        }

        /// <inheritdoc/>
        /// <remarks>
        /// Generates a single <c>Auditsystemtable</c> record for INSERT, UPDATE, or DELETE operations
        /// on supported entity types (<c>Plantstatehistory</c>, <c>Plantobservation</c>).
        /// Performs row-level auditing ("ALL" column) using the <see cref="IAuditHelperService"/>.
        /// <c>CropId</c> is explicitly set to <c>null</c> for entries generated by this instance.
        /// </remarks>
        public IEnumerable<object> GenerateEntries(EntityEntry entry, AuditMetadata metadata)
        {
            // Safety check for type
            if (!(entry.Entity is Plantstatehistory || entry.Entity is Plantobservation))
            {
                _logger.LogWarning("AuditSystemTableGenerator potentially called with unexpected type (check logic): {EntityType}", entry.Entity.GetType().Name);
                return Enumerable.Empty<object>();
            }

            // Create the base audit entity instance
            var audit = new Auditsystemtable
            {
                // Common metadata
                Performedat = metadata.PerformedAt,
                Performedby = metadata.UserId,
                Performedbyip = metadata.IpAddress,
                Useragent = metadata.UserAgent,

                // Specific audit info
                Tablename = entry.Metadata.GetTableName() ?? entry.Entity.GetType().Name,
                Columnname = "ALL",
                Action = entry.State.ToString().ToUpperInvariant(),
                Recordid = _auditHelper.GetPrimaryKeyValue(entry) ?? 0, // Get PK early
                Cropid = null // Explicitly null for system tables
            };

            _logger.LogInformation("Generating AuditSystemTable for {TableName} ID: {RecordId}, Action: {Action}",
                                   audit.Tablename, audit.Recordid, audit.Action);

            // Populate OldValue and NewValue using the helper method
            if (!TryPopulateAuditValues(audit, entry))
            {
                // Helper returned false, likely due to unexpected state - already logged by helper.
                return Enumerable.Empty<object>();
            }

            // Return the populated audit entry
            return new List<object> { audit };
        }

        /// <summary>
        /// Populates the OldValue and NewValue properties of the audit entry based on the entity state.
        /// </summary>
        /// <param name="audit">The <see cref="Auditsystemtable"/> object to populate.</param>
        /// <param name="entry">The <see cref="EntityEntry"/> containing the changes.</param>
        /// <returns>True if values were populated successfully, false if the entity state was unexpected.</returns>
        private bool TryPopulateAuditValues(Auditsystemtable audit, EntityEntry entry)
        {
            // Note: Excluded properties parameter is commented out in original, kept same here.
            // Consider adding `IEnumerable<string>? excludedProps = null` if needed.
            switch (entry.State)
            {
                case EntityState.Added:
                    audit.Oldvalue = null;
                    audit.Newvalue = _auditHelper.SerializePropertyValueDictionary(
                                         _auditHelper.GetValuesDictionary(entry.CurrentValues /*, excludedProps */)
                                     );
                    // Override RecordId for Added entities as it's not available yet from DB
                    audit.Recordid = 0;
                    return true;

                case EntityState.Deleted:
                    audit.Oldvalue = _auditHelper.SerializePropertyValueDictionary(
                                         _auditHelper.GetValuesDictionary(entry.OriginalValues /*, excludedProps */)
                                     );
                    audit.Newvalue = null;
                    // RecordId was already obtained when 'audit' was created
                    return true;

                case EntityState.Modified:
                    audit.Oldvalue = _auditHelper.SerializePropertyValueDictionary(
                                         _auditHelper.GetValuesDictionary(entry.OriginalValues /*, excludedProps */)
                                     );
                    audit.Newvalue = _auditHelper.SerializePropertyValueDictionary(
                                         _auditHelper.GetValuesDictionary(entry.CurrentValues /*, excludedProps */)
                                     );
                    // RecordId was already obtained when 'audit' was created
                    return true;

                default:
                    // Logs a warning for unexpected entity states.
                    _logger.LogWarning("Unexpected entity state {EntityState} detected for {TableName} ID: {RecordId} in AuditSystemTableGenerator.",
                                       entry.State, audit.Tablename, audit.Recordid);
                    return false; // Indicate failure/unexpected state
            }
        }
    }
}