using ArandanoIRT_Backend.Application.Interfaces.Auditing;
using ArandanoIRT_Backend.Infrastructure.Data; 
using Microsoft.EntityFrameworkCore; 
using Microsoft.EntityFrameworkCore.ChangeTracking; 

namespace ArandanoIRT_Backend.Infrastructure.Persistence.Auditing
{
    /// <summary>
    /// Implements <see cref="IAuditEntryGenerator"/> to create audit trail entries
    /// specifically for changes made to <c>Crop</c> entities.
    /// </summary>
    public class AuditCropGenerator : IAuditEntryGenerator
    {
        private readonly IAuditHelperService _auditHelper;
        private readonly ILogger<AuditCropGenerator> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditCropGenerator"/> class.
        /// </summary>
        /// <param name="auditHelper">The helper service for common auditing tasks like serialization and ID retrieval.</param>
        /// <param name="logger">The logger for recording information and warnings.</param>
        /// <exception cref="ArgumentNullException">Thrown if auditHelper or logger is null.</exception>
        public AuditCropGenerator(IAuditHelperService auditHelper, ILogger<AuditCropGenerator> logger)
        {
            // Injects required services.
            _auditHelper = auditHelper ?? throw new ArgumentNullException(nameof(auditHelper));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <inheritdoc/>
        /// <remarks>
        /// This generator specifically handles entities of type <c>Crop</c>.
        /// </remarks>
        public bool CanHandle(EntityEntry entry)
        {
            // Checks if the entry's entity is of the target type Crop.
            return entry.Entity is Crop;
        }

        /// <inheritdoc/>
        /// <remarks>
        /// Generates a single <c>Auditcrop</c> record for INSERT, UPDATE, or DELETE operations on a <c>Crop</c> entity.
        /// It currently performs row-level auditing by setting <c>ColumnName</c> to "ALL" and serializing
        /// the entire entity's original/current values using the <see cref="IAuditHelperService"/>.
        /// For INSERT operations, RecordId and CropId are set to placeholders (0/null) as they are not yet available.
        /// </remarks>
        public IEnumerable<object> GenerateEntries(EntityEntry entry, AuditMetadata metadata)
        {
            // Ensures the entity is of the expected type (Crop), performing a safety check.
            if (entry.Entity is not Crop cropEntity) // Uses pattern matching for type check and assignment.
            {
                // Logs a warning if incorrectly called (though CanHandle should typically prevent this).
                _logger.LogWarning("AuditCropGenerator called with unexpected entity type: {EntityType}", entry.Entity.GetType().Name);
                return Enumerable.Empty<object>(); // Returns an empty collection, generating no audit entry.
            }

            // Creates the database audit entity instance (using the assumed context type 'Auditcrop').
            var audit = new Auditcrop
            {
                // Populates common audit fields from the provided metadata.
                Performedat = metadata.PerformedAt,
                Performedby = metadata.UserId,
                Performedbyip = metadata.IpAddress,
                Useragent = metadata.UserAgent,
                // Sets column name to "ALL", indicating row-level auditing for this implementation.
                Columnname = "ALL",
                // IdAuditCrop is expected to be generated by the database upon insertion.
            };

            // Determines action type and populates relevant fields based on the entity's state.
            switch (entry.State)
            {
                case EntityState.Added:
                    audit.Action = "INSERT";
                    audit.Oldvalue = null; // No old value for inserts.
                    // Serializes the current property values using the helper service.
                    audit.Newvalue = _auditHelper.SerializePropertyValueDictionary(
                                         _auditHelper.GetValuesDictionary(entry.CurrentValues) // Assumes default exclusions are applied by helper.
                                     );
                    // IDs are not yet available for newly added entities before saving.
                    audit.Recordid = 0; // Uses 0 as a placeholder for the record ID.
                    audit.Cropid = null; // Uses null as a placeholder for the crop ID.
                    _logger.LogInformation("Generating INSERT audit entry for Crop entity.");
                    break;

                case EntityState.Deleted:
                    audit.Action = "DELETE";
                    // Serializes the original property values using the helper service.
                    audit.Oldvalue = _auditHelper.SerializePropertyValueDictionary(
                                         _auditHelper.GetValuesDictionary(entry.OriginalValues)
                                     );
                    audit.Newvalue = null; // No new value for deletes.
                    // Retrieves IDs using the helper service (likely from original values).
                    audit.Recordid = _auditHelper.GetPrimaryKeyValue(entry);
                    // For Crop entities, the CropId is the same as the primary key (RecordId).
                    audit.Cropid = audit.Recordid;
                    _logger.LogInformation("Generating DELETE audit entry for Crop ID: {CropId}", audit.Recordid);
                    break;

                case EntityState.Modified:
                    audit.Action = "UPDATE";
                    // Serializes both original and current values using the helper service.
                    audit.Oldvalue = _auditHelper.SerializePropertyValueDictionary(
                                         _auditHelper.GetValuesDictionary(entry.OriginalValues)
                                     );
                    audit.Newvalue = _auditHelper.SerializePropertyValueDictionary(
                                         _auditHelper.GetValuesDictionary(entry.CurrentValues)
                                     );
                    // Retrieves IDs using the helper service.
                    audit.Recordid = _auditHelper.GetPrimaryKeyValue(entry);
                    audit.Cropid = audit.Recordid;
                    _logger.LogInformation("Generating UPDATE audit entry for Crop ID: {CropId}", audit.Recordid);
                    break;

                default:
                    // Logs a warning for any unexpected entity states encountered.
                    _logger.LogWarning("Unexpected entity state {EntityState} detected for Crop ID: {CropId} in AuditCropGenerator.",
                                       entry.State, _auditHelper.GetPrimaryKeyValue(entry)); // Attempt to get ID even for unexpected states
                    return Enumerable.Empty<object>(); // Does not generate an audit entry for unexpected states.
            }

            // Returns a list containing the single generated audit entry object.
            return new List<object> { audit };
        }
    }
}