using ArandanoIRT_Backend.Application.Interfaces.Auditing;
using ArandanoIRT_Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.Extensions.Logging;

namespace ArandanoIRT_Backend.Infrastructure.Persistence.Auditing
{
    /// <summary>
    /// Implements <see cref="IAuditEntryGenerator"/> to create audit trail entries
    /// in the <c>Auditsystemtable</c> for changes made to specific "system" or related data entities
    /// like <c>Plantstatehistory</c> and <c>Plantobservation</c>.
    /// </summary>
    public class AuditSystemTableGenerator : IAuditEntryGenerator
    {
        private readonly IAuditHelperService _auditHelper;
        private readonly ILogger<AuditSystemTableGenerator> _logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditSystemTableGenerator"/> class.
        /// </summary>
        /// <param name="auditHelper">The helper service for common auditing tasks.</param>
        /// <param name="logger">The logger for recording information and warnings.</param>
        /// <exception cref="ArgumentNullException">Thrown if auditHelper or logger is null.</exception>
        public AuditSystemTableGenerator(IAuditHelperService auditHelper, ILogger<AuditSystemTableGenerator> logger)
        {
            _auditHelper = auditHelper ?? throw new ArgumentNullException(nameof(auditHelper));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <inheritdoc/>
        /// <remarks>
        /// This generator handles only the specified entity types:
        /// <c>Plantstatehistory</c> and <c>Plantobservation</c>.
        /// It explicitly does NOT handle Status, TableRelation, FailedLoginAttempt, DeviceLog, etc.
        /// </remarks>
        public bool CanHandle(EntityEntry entry)
        {
            // Handles only the specified entity types.
            return entry.Entity is Plantstatehistory ||
                   entry.Entity is Plantobservation;
            // Does NOT include Status, TableRelation, FailedLoginAttempt, DeviceLog
        }

        /// <inheritdoc/>
        /// <remarks>
        /// Generates a single <c>Auditsystemtable</c> record for INSERT, UPDATE, or DELETE operations
        /// on supported entity types (<c>Plantstatehistory</c>, <c>Plantobservation</c>).
        /// Performs row-level auditing ("ALL" column) using the <see cref="IAuditHelperService"/>.
        /// <c>CropId</c> is explicitly set to <c>null</c> for entries generated by this instance.
        /// </remarks>
        public IEnumerable<object> GenerateEntries(EntityEntry entry, AuditMetadata metadata)
        {
            // Safety check for type (although CanHandle should prevent incorrect types).
            if (entry.Entity is not Plantstatehistory &&
                entry.Entity is not Plantobservation)
            {
                _logger.LogWarning("AuditSystemTableGenerator potentially called with unexpected type (check logic): {EntityType}", entry.Entity.GetType().Name);
                return Enumerable.Empty<object>();
            }

            // Creates the audit database entity instance ('Auditsystemtable').
            var audit = new Auditsystemtable();

            // Populates common audit metadata.
            audit.Performedat = metadata.PerformedAt;
            audit.Performedby = metadata.UserId;
            audit.Performedbyip = metadata.IpAddress;
            audit.Useragent = metadata.UserAgent;

            // Sets specific audit information for the system table change.
            audit.Tablename = entry.Metadata.GetTableName() ?? entry.Entity.GetType().Name; // Gets table name.
            audit.Columnname = "ALL"; // Sets column name to "ALL" for row-level auditing.
            audit.Action = entry.State.ToString().ToUpperInvariant(); // Action based on entity state.
            audit.Recordid = _auditHelper.GetPrimaryKeyValue(entry) ?? 0; // Retrieves the primary key of the affected record.
            audit.Cropid = null; // Explicitly sets CropId to null for these "system" table audits.

            // Logs the generation attempt.
            _logger.LogInformation("Generating AuditSystemTable for {TableName} ID: {RecordId}, Action: {Action}",
                                   audit.Tablename, audit.Recordid, audit.Action);

            // Exclude properties if necessary (unlikely here).
            // IEnumerable<string>? excludedProps = null;

            // Populates OldValue and NewValue based on the entity state.
            switch (entry.State)
            {
                case EntityState.Added:
                    audit.Oldvalue = null;
                    audit.Newvalue = _auditHelper.SerializePropertyValueDictionary(
                                         _auditHelper.GetValuesDictionary(entry.CurrentValues /*, excludedProps */)
                                     );
                    audit.Recordid = 0; // ID does not exist yet for added entities.
                    break;

                case EntityState.Deleted:
                    audit.Oldvalue = _auditHelper.SerializePropertyValueDictionary(
                                        _auditHelper.GetValuesDictionary(entry.OriginalValues /*, excludedProps */)
                                     );
                    audit.Newvalue = null;
                    // RecordId was already obtained using the helper.
                    break;

                case EntityState.Modified:
                    audit.Oldvalue = _auditHelper.SerializePropertyValueDictionary(
                                        _auditHelper.GetValuesDictionary(entry.OriginalValues /*, excludedProps */)
                                     );
                    audit.Newvalue = _auditHelper.SerializePropertyValueDictionary(
                                         _auditHelper.GetValuesDictionary(entry.CurrentValues /*, excludedProps */)
                                     );
                    // RecordId was already obtained using the helper.
                    break;

                default:
                    // Logs a warning for unexpected entity states.
                    _logger.LogWarning("Unexpected entity state {EntityState} detected for {TableName} ID: {RecordId} in AuditSystemTableGenerator.",
                                       entry.State, audit.Tablename, audit.Recordid);
                    return Enumerable.Empty<object>(); // Does not generate an audit entry.
            }

            // Returns a list containing the single generated audit entry object.
            return new List<object> { audit };
        }
    }
}