using ArandanoIRT_Backend.Application.DTOs.Device;
using ArandanoIRT_Backend.Domain.Entities;
using UAParser;

namespace ArandanoIRT_Backend.Application.Mappings
{
    /// <summary>
    /// Provides static mapping methods for device related DTOs and Entities.
    /// </summary>
    public static class DeviceMapping
    {
        /// <summary>
        /// Maps a CreateDeviceDto to a new DeviceDataEntity.
        /// Assumes required validation has passed on the DTO.
        /// </summary>
        /// <param name="dto">The DTO containing device creation data.</param>
        /// <param name="registeredAt">The registration timestamp (UTC).</param>
        /// <param name="registeredByUserId">The ID of the user registering the device (nullable).</param>
        /// <returns>A new DeviceDataEntity instance, ready for further processing (e.g., saving to repository).</returns>
        public static DeviceDataEntity ToDeviceDataEntity(this CreateDeviceDto dto, DateTime registeredAt, int? registeredByUserId)
        {
            return new DeviceDataEntity(
                idDeviceData: 0, // ID is generated by the database
                nameDevice: dto.NameDevice,
                descriptionDevice: dto.DescriptionDevice, // DescriptionDevice is string? in entity and DTO
                dataCollectionTime: dto.DataCollectionTime,
                registeredAt: registeredAt,
                registeredBy: registeredByUserId,
                statusId: dto.StatusId, // Initial status comes from DTO
                cropId: dto.CropId,
                plantId: dto.PlantId
            );
        }

        /// <summary>
        /// Maps a DeviceDataEntity to a DeviceDto for listing purposes.
        /// Includes mapping for StatusName and CropName if available (requires joining/including data before mapping).
        /// </summary>
        /// <param name="entity">The DeviceDataEntity.</param>
        /// <param name="statusName">The name of the device's status (optional).</param>
        /// <param name="cropName">The name of the associated crop (optional).</param>
        /// <returns>A DeviceDto for list views.</returns>
        public static DeviceDto ToDeviceDto(this DeviceDataEntity entity, string? statusName = null, string? cropName = null)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "DeviceData entity cannot be null for mapping to DeviceDto.");
            }

            return new DeviceDto
            {
                IdDeviceData = entity.IdDeviceData,
                NameDevice = entity.NameDevice,
                DescriptionDevice = entity.DescriptionDevice,
                StatusId = entity.StatusId,
                CropId = entity.CropId,
                RegisteredAt = entity.RegisteredAt,
                // Mapped 'name' fields from related data if provided
                StatusName = statusName,
                CropName = cropName
            };
        }

        /// <summary>
        /// Maps a DeviceDataEntity to a DeviceDetailDto for detailed views.
        /// Includes mapping for name fields from related data if available (requires joining/including data).
        /// </summary>
        /// <param name="entity">The DeviceDataEntity.</param>
        /// <param name="statusName">The name of the device's status (optional).</param>
        /// <param name="registeredByName">The name of the user who registered the device (optional).</param>
        /// <param name="updatedByName">The name of the user who last updated the device (optional).</param>
        /// <param name="cropName">The name of the associated crop (optional).</param>
        /// <param name="plantName">The name of the associated plant (optional).</param>
        /// <returns>A DeviceDetailDto for detail views.</returns>
        public static DeviceDetailDto ToDeviceDetailDto(
            this DeviceDataEntity entity,
            string? statusName = null,
            string? registeredByName = null,
            string? updatedByName = null,
            string? cropName = null,
            string? plantName = null)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity), "DeviceData entity cannot be null for mapping to DeviceDetailDto.");
            }

            return new DeviceDetailDto
            {
                IdDeviceData = entity.IdDeviceData,
                NameDevice = entity.NameDevice,
                DescriptionDevice = entity.DescriptionDevice, // DescriptionDevice is string?
                DataCollectionTime = entity.DataCollectionTime,
                StatusId = entity.StatusId,
                RegisteredAt = entity.RegisteredAt,
                RegisteredBy = entity.RegisteredBy,
                UpdatedAt = entity.UpdatedAt, // UpdatedAt is DateTime?
                UpdatedBy = entity.UpdatedBy, // UpdatedBy is int?
                CropId = entity.CropId, // CropId is int?
                PlantId = entity.PlantId, // PlantId is int?
                // Mapped 'name' fields from related data if provided
                StatusName = statusName,
                RegisteredByName = registeredByName,
                UpdatedByName = updatedByName,
                CropName = cropName,
                PlantName = plantName
            };
        }

        /// <summary>
        /// Maps an UpdateDeviceDto onto an existing DeviceDataEntity.
        /// This is useful when updating an entity retrieved from the repository
        /// with data from a DTO, preserving properties not present in the DTO
        /// and handling UpdatedAt/UpdatedBy.
        /// </summary>
        /// <param name="dto">The DTO containing the updated data.</param>
        /// <param name="entityToUpdate">The existing DeviceDataEntity to update.</param>
        /// <param name="updatedAt">The timestamp of the update (UTC).</param>
        /// <param name="updatedByUserId">The ID of the user performing the update (nullable).</param>
        public static void MapToDeviceDataEntity(this UpdateDeviceDto dto, DeviceDataEntity entityToUpdate, DateTime updatedAt, int? updatedByUserId)
        {
            if (dto == null) throw new ArgumentNullException(nameof(dto));
            if (entityToUpdate == null) throw new ArgumentNullException(nameof(entityToUpdate));

            // Use reflection to set the private setters on the domain entity.
            // This keeps the entity's encapsulation while allowing mapping from a DTO.
            typeof(DeviceDataEntity).GetProperty(nameof(DeviceDataEntity.NameDevice))?.SetValue(entityToUpdate, dto.NameDevice, null);
            typeof(DeviceDataEntity).GetProperty(nameof(DeviceDataEntity.DescriptionDevice))?.SetValue(entityToUpdate, dto.DescriptionDevice, null);
            typeof(DeviceDataEntity).GetProperty(nameof(DeviceDataEntity.DataCollectionTime))?.SetValue(entityToUpdate, dto.DataCollectionTime, null);
            typeof(DeviceDataEntity).GetProperty(nameof(DeviceDataEntity.StatusId))?.SetValue(entityToUpdate, dto.StatusId, null);
            typeof(DeviceDataEntity).GetProperty(nameof(DeviceDataEntity.CropId))?.SetValue(entityToUpdate, dto.CropId, null);
            typeof(DeviceDataEntity).GetProperty(nameof(DeviceDataEntity.PlantId))?.SetValue(entityToUpdate, dto.PlantId, null);

            // Set the update tracking fields.
            typeof(DeviceDataEntity).GetProperty(nameof(DeviceDataEntity.UpdatedAt))?.SetValue(entityToUpdate, updatedAt, null);
            typeof(DeviceDataEntity).GetProperty(nameof(DeviceDataEntity.UpdatedBy))?.SetValue(entityToUpdate, updatedByUserId, null);
        }


        // --- Mappings for Device Communication DTOs to Entities ---

        /// <summary>
        /// Maps an AmbientDataDto to a new SensorDataEntity.
        /// Assumes required validation has passed on the DTO.
        /// Requires PlantId, CropId, and RecordedAt which come from the device context/token.
        /// </summary>
        /// <param name="dto">The DTO containing environmental sensor data.</param>
        /// <param name="plantId">The ID of the associated plant (nullable).</param>
        /// <param name="cropId">The ID of the associated crop (nullable).</param>
         /// <param name="recordedAt">The timestamp when the data was recorded (UTC).</param>
        /// <returns>A new SensorDataEntity instance.</returns>
        public static SensorDataEntity ToSensorDataEntity(this AmbientDataDto dto, int? plantId, int? cropId, DateTime recordedAt)
        {
            if (dto == null) throw new ArgumentNullException(nameof(dto));

            return new SensorDataEntity(
                idSensorData: 0, // DB will generate ID
                temperature: dto.Temperature, // Using float
                humidity: dto.Humidity, // Using float
                lightIntensity: dto.Light, // Using float
                cityTemperature: null, // City data is not in this DTO
                cityHumidity: null, // City data is not in this DTO
                recordedAt: recordedAt,
                plantId: plantId,
                cropId: cropId
            );
            // Entity constructor validates humidity and light intensity ranges.
        }


        /// <summary>
        /// Maps a ThermalDataDto and image byte array to a new ThermalDataEntity.
        /// Assumes required validation has passed on the DTO.
        /// Requires PlantId, CropId, and RecordedAt which come from the device context/token.
        /// </summary>
        /// <param name="dto">The DTO containing thermal data and statistics (JSON part).</param>
        /// <param name="rgbImageData">The byte array of the RGB image.</param>
        /// <param name="thermalImageDataJson">The original JSON string of the thermal image data (for DB storage).</param>
        /// <param name="plantId">The ID of the associated plant (nullable).</param>
        /// <param name="cropId">The ID of the associated crop (nullable).</param>
        /// <param name="recordedAt">The timestamp when the data was recorded (UTC).</param>
        /// <returns>A new ThermalDataEntity instance.</returns>
        public static ThermalDataEntity ToThermalDataEntity(this ThermalDataDto dto, byte[]? rgbImageData, string thermalImageDataJson, int? plantId, int? cropId, DateTime recordedAt)
        {
            if (dto == null) throw new ArgumentNullException(nameof(dto));
            // Validation for rgbImageData and thermalImageDataJson is handled in the Entity constructor.

            return new ThermalDataEntity(
                idThermalData: 0, // DB will generate ID
                thermalImageData: thermalImageDataJson, // Store the original JSON string
                rgbImageData: rgbImageData ?? [], 
                recordedAt: recordedAt,
                plantId: plantId,
                cropId: cropId
            );
            // Entity constructor validates thermalImageData is not null/whitespace and rgbImageData is not null.
        }


        /// <summary>
        /// Maps a DeviceLogEntryDto to a new DeviceLogEntity.
        /// Assumes required validation has passed on the DTO.
        /// Requires the device ID sending the log.
        /// </summary>
        /// <param name="dto">The DTO containing device log data.</param>
        /// <param name="deviceId">The ID of the device sending the log.</param>
        /// <returns>A new DeviceLogEntity instance.</returns>
        public static DeviceLogEntity ToDeviceLogEntity(this DeviceLogEntryDto dto, int deviceId)
        {
            if (dto == null) throw new ArgumentNullException(nameof(dto));
            if (deviceId <= 0) throw new ArgumentOutOfRangeException(nameof(deviceId), "Device ID must be positive.");

            return new DeviceLogEntity(
                idDeviceLog: 0, // DB will generate ID
                deviceId: deviceId,
                logType: dto.LogType,
                logMessage: dto.LogMessage,
                logTimestamp: dto.LogTimestamp // Assuming timestamp from device is used (and is UTC)
            );
        }
    }
}