using ArandanoIRT_Backend.Infrastructure.Utilities; 
using FluentAssertions;
using Xunit;

namespace ArandanoIRT_Backend.Tests.Unit.Infrastructure.Utilities
{
    /// <summary>
    /// Contains unit tests for the <see cref="BCryptPasswordHasher"/> class.
    /// </summary>
    public class BCryptPasswordHasherTests
    {
        /// <summary>
        /// The instance of the BCryptPasswordHasher class under test.
        /// </summary>
        private readonly BCryptPasswordHasher _hasher = new BCryptPasswordHasher();

        /// <summary>
        /// Tests that the Hash method returns a non-empty string (the hash)
        /// when provided with a valid, non-empty password.
        /// </summary>
        [Fact]
        public void Hash_WithValidPassword_ShouldReturnNonEmptyHash()
        {
            // Arrange
            // Defines a valid password string.
            var password = "validPassword123";

            // Act
            // Calls the Hash method on the hasher instance.
            var hash = _hasher.Hash(password);

            // Assert
            // Uses FluentAssertions to check that the returned hash is not null or empty.
            hash.Should().NotBeNullOrEmpty();
            // Also verifies that the generated hash is different from the original password.
            hash.Should().NotBe(password);
            // Performs a basic check to see if the hash starts with a common BCrypt prefix ($2a$, $2b$, $2y$).
            hash.Should().StartWith("$2");
        }

        /// <summary>
        /// Tests that the Hash method throws an <see cref="ArgumentException"/>
        /// when the provided password is null.
        /// </summary>
        [Fact]
        public void Hash_WithNullPassword_ShouldThrowArgumentException()
        {
            // Arrange
            // Defines a null password.
            string? password = null;

            // Act
            // Defines the action that calls the Hash method with the null password.
            // Uses the null-forgiving operator as an exception is expected before use.
            Action act = () => _hasher.Hash(password!);

            // Assert
            // Uses FluentAssertions to check that the action throws the expected exception type.
            // Checks that the exception message starts with the expected text.
            act.Should().Throw<ArgumentException>()
               .WithMessage("Password cannot be empty.*");
        }

        /// <summary>
        /// Tests that the Hash method throws an <see cref="ArgumentException"/>
        /// when the provided password is an empty string.
        /// </summary>
        [Fact]
        public void Hash_WithEmptyPassword_ShouldThrowArgumentException()
        {
            // Arrange
            // Defines an empty password string.
            var password = "";

            // Act
            // Defines the action that calls the Hash method with the empty password.
            Action act = () => _hasher.Hash(password);

            // Assert
            // Uses FluentAssertions to check that the action throws the expected exception.
            act.Should().Throw<ArgumentException>()
               .WithMessage("Password cannot be empty.*");
        }

        /// <summary>
        /// Tests that the Hash method throws an <see cref="ArgumentException"/>
        /// when the provided password consists only of whitespace.
        /// </summary>
        [Fact]
        public void Hash_WithWhitespacePassword_ShouldThrowArgumentException()
        {
            // Arrange
            // Defines a password string containing only whitespace.
            var password = "    ";

            // Act
            // Defines the action that calls the Hash method with the whitespace password.
            Action act = () => _hasher.Hash(password);

            // Assert
            // Uses FluentAssertions to check that the action throws the expected exception.
            act.Should().Throw<ArgumentException>()
               .WithMessage("Password cannot be empty.*");
        }

        /// <summary>
        /// Tests that the Verify method returns true when comparing a correct password
        /// against its corresponding BCrypt hash generated by the Hash method.
        /// </summary>
        [Fact]
        public void Verify_WithCorrectPassword_ShouldReturnTrue()
        {
            // Arrange
            // Defines a valid password.
            var password = "mySecretPassword";
            // Generates the hash for the password using the same hasher instance.
            var hash = _hasher.Hash(password);

            // Act
            // Calls the Verify method with the generated hash and the original password.
            var result = _hasher.Verify(hash, password);

            // Assert
            // Uses FluentAssertions to check that the result is true.
            result.Should().BeTrue();
        }

        /// <summary>
        /// Tests that the Verify method returns false when comparing an incorrect password
        /// against a valid BCrypt hash.
        /// </summary>
        [Fact]
        public void Verify_WithIncorrectPassword_ShouldReturnFalse()
        {
            // Arrange
            // Defines a valid password and generates its hash.
            var correctPassword = "mySecretPassword";
            var hash = _hasher.Hash(correctPassword);
            // Defines an incorrect password.
            var incorrectPassword = "wrongPassword";

            // Act
            // Calls the Verify method with the hash and the incorrect password.
            var result = _hasher.Verify(hash, incorrectPassword);

            // Assert
            // Uses FluentAssertions to check that the result is false.
            result.Should().BeFalse();
        }

        /// <summary>
        /// Tests that the Verify method returns false when the provided hash string is null.
        /// </summary>
        [Fact]
        public void Verify_WithNullHash_ShouldReturnFalse()
        {
            // Arrange
            // Defines a null hash and a valid password.
            string? hash = null;
            var password = "anyPassword";

            // Act
            // Calls the Verify method with the null hash.
            // Uses the null-forgiving operator for the test setup.
            var result = _hasher.Verify(hash!, password);

            // Assert
            // Uses FluentAssertions to check that the result is false.
            result.Should().BeFalse();
        }

        /// <summary>
        /// Tests that the Verify method returns false when the provided password to check is null.
        /// </summary>
        [Fact]
        public void Verify_WithNullProvidedPassword_ShouldReturnFalse()
        {
            // Arrange
            // Defines a valid hash and a null provided password.
            var hash = _hasher.Hash("anyPassword");
            string? providedPassword = null;

            // Act
            // Calls the Verify method with the null provided password.
            // Uses the null-forgiving operator for the test setup.
            var result = _hasher.Verify(hash, providedPassword!);

            // Assert
            // Uses FluentAssertions to check that the result is false.
            result.Should().BeFalse();
        }

        /// <summary>
        /// Tests that the Verify method returns false when the provided hash string is empty.
        /// </summary>
        [Fact]
        public void Verify_WithEmptyHash_ShouldReturnFalse()
        {
            // Arrange
            // Defines an empty hash and a valid password.
            var hash = "";
            var password = "anyPassword";

            // Act
            // Calls the Verify method with the empty hash.
            var result = _hasher.Verify(hash, password);

            // Assert
            // Uses FluentAssertions to check that the result is false.
            result.Should().BeFalse();
        }

        /// <summary>
        /// Tests that the Verify method returns false when the provided password to check is empty.
        /// </summary>
        [Fact]
        public void Verify_WithEmptyProvidedPassword_ShouldReturnFalse()
        {
            // Arrange
            // Defines a valid hash and an empty provided password.
            var hash = _hasher.Hash("anyPassword");
            var providedPassword = "";

            // Act
            // Calls the Verify method with the empty provided password.
            var result = _hasher.Verify(hash, providedPassword);

            // Assert
            // Uses FluentAssertions to check that the result is false.
            result.Should().BeFalse();
        }

        /// <summary>
        /// Tests that the Verify method returns false when provided with a hash string
        /// that does not conform to the expected BCrypt format.
        /// It also ensures no unexpected exception is thrown directly from the Verify method itself.
        /// </summary>
        /// <param name="invalidHash">An invalid or improperly formatted hash string.</param>
        [Theory]
        [InlineData("invalidHashFormat")]                // Example: Not starting with BCrypt prefix
        [InlineData("$2a$05$invalidSaltAndHashPart")]    // Example: Incorrect salt/hash format structure
        [InlineData("")]                                 // Example: Empty hash
        [InlineData("    ")]                             // Example: Whitespace hash
        public void Verify_WithInvalidHashFormat_ShouldReturnFalse(string invalidHash)
        {
            // Arrange
            // Defines a valid password to compare against.
            var password = "anyPassword";

            // Act
            // Calls the Verify method with the invalid hash format.
            var result = _hasher.Verify(invalidHash, password);

            // Assert
            // Uses FluentAssertions to check that the result is false.
            result.Should().BeFalse();
        }
    }
}