namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a single audit trail record tracking changes specifically related to person (user) entities or data,
    /// associated with a particular crop. Note: This specific audit entity does not track old/new values.
    /// </summary>
    public class AuditPersonEntity
    {
        /// <summary>
        /// Gets the unique identifier for this person audit log entry.
        /// </summary>
        public int IdAuditPerson { get; private set; }

        /// <summary>
        /// Gets the name of the column or property within the person entity that was changed or involved in the action.
        /// </summary>
        public string ColumnName { get; private set; }

        /// <summary>
        /// Gets the identifier (primary key) of the specific person record that was affected.
        /// </summary>
        public int RecordId { get; private set; }

        /// <summary>
        /// Gets the identifier of the crop to which the audited person belongs or is related.
        /// </summary>
        public int CropId { get; private set; }

        /// <summary>
        /// Gets the type of action performed (e.g., "LOGIN", "UPDATE_PROFILE", "PASSWORD_RESET").
        /// </summary>
        public string Action { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the action was performed. Nullable.
        /// </summary>
        public DateTime? PerformedAt { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the user who performed the action (can be the user themselves or an admin). Nullable.
        /// </summary>
        public int? PerformedBy { get; private set; }

        /// <summary>
        /// Gets the IP address from which the action was performed, if available. Nullable.
        /// </summary>
        public string? PerformedByIp { get; private set; }

        /// <summary>
        /// Gets the user agent string of the client that performed the action, if available. Nullable.
        /// </summary>
        public string? UserAgent { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditPersonEntity"/> class with detailed audit information for a person-related action.
        /// </summary>
        /// <param name="idAuditPerson">The unique ID for this audit record (often generated by the database).</param>
        /// <param name="columnName">The name of the column/property involved in the action.</param>
        /// <param name="recordId">The ID of the affected person record.</param>
        /// <param name="cropId">The ID of the crop this person relates to.</param>
        /// <param name="action">The action performed (e.g., "LOGIN").</param>
        /// <param name="performedAt">The timestamp of the action (nullable).</param>
        /// <param name="performedBy">The ID of the user performing the action (nullable).</param>
        /// <param name="performedByIp">The IP address associated with the action (nullable).</param>
        /// <param name="userAgent">The user agent of the client, if applicable (nullable).</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="columnName"/> is null or whitespace (Spanish message: "El nombre de la columna es requerido.").
        /// Thrown if <paramref name="action"/> is null or whitespace (Spanish message: "La acción es requerida.").
        /// </exception>
        public AuditPersonEntity(
            int idAuditPerson,
            string columnName,
            int recordId,
            int cropId,
            string action,
            DateTime? performedAt,
            int? performedBy,
            string? performedByIp,
            string? userAgent)
        {
            // Validates that required string arguments are provided.
            if (string.IsNullOrWhiteSpace(columnName))
            {
                throw new ArgumentException("The column name is required.", nameof(columnName));
            }
            if (string.IsNullOrWhiteSpace(action))
            {
                throw new ArgumentException("The action is required.", nameof(action));
            }

            // Assigns validated parameters to the corresponding properties.
            IdAuditPerson = idAuditPerson;
            ColumnName = columnName;
            RecordId = recordId;
            CropId = cropId;
            Action = action;
            PerformedAt = performedAt;
            PerformedBy = performedBy;
            PerformedByIp = performedByIp;
            UserAgent = userAgent;
        }
    }
}