namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a single audit trail record tracking changes specifically related to device entities or data,
    /// typically associated with a particular crop.
    /// </summary>
    public class AuditDeviceEntity
    {
        /// <summary>
        /// Gets the unique identifier for this device audit log entry.
        /// </summary>
        public int IdAuditDevice { get; private set; }

        /// <summary>
        /// Gets the name of the column or property within the device entity that was changed.
        /// </summary>
        public string ColumnName { get; private set; }

        /// <summary>
        /// Gets the identifier (primary key) of the specific device record that was affected.
        /// </summary>
        public int RecordId { get; private set; }

        /// <summary>
        /// Gets the identifier of the crop to which the audited device belongs or is related.
        /// </summary>
        public int CropId { get; private set; }

        /// <summary>
        /// Gets the type of action performed (e.g., "REGISTER", "UPDATE_CONFIG", "DELETE").
        /// </summary>
        public string Action { get; private set; }

        /// <summary>
        /// Gets the value of the column/property before the change, if applicable (e.g., for UPDATE actions). Null otherwise.
        /// </summary>
        public string? OldValue { get; private set; }

        /// <summary>
        /// Gets the value of the column/property after the change, if applicable (e.g., for creation or UPDATE actions). Null otherwise.
        /// </summary>
        public string? NewValue { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the action was performed. Nullable.
        /// </summary>
        public DateTime? PerformedAt { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the user who performed the action, if available (e.g., linking a device). Nullable.
        /// </summary>
        public int? PerformedBy { get; private set; }

        /// <summary>
        /// Gets the IP address from which the action was performed or originated, if available. Nullable.
        /// </summary>
        public string? PerformedByIp { get; private set; }

        /// <summary>
        /// Gets the user agent string of the client that performed the action, if applicable. Nullable.
        /// </summary>
        public string? UserAgent { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditDeviceEntity"/> class with detailed audit information for a device-related change.
        /// </summary>
        /// <param name="idAuditDevice">The unique ID for this audit record (often generated by the database).</param>
        /// <param name="columnName">The name of the column/property changed in the device entity.</param>
        /// <param name="recordId">The ID of the affected device record.</param>
        /// <param name="cropId">The ID of the crop this device relates to.</param>
        /// <param name="action">The action performed (e.g., "UPDATE_CONFIG").</param>
        /// <param name="oldValue">The previous value (nullable).</param>
        /// <param name="newValue">The new value (nullable).</param>
        /// <param name="performedAt">The timestamp of the action (nullable).</param>
        /// <param name="performedBy">The ID of the user performing the action (nullable).</param>
        /// <param name="performedByIp">The IP address associated with the action (nullable).</param>
        /// <param name="userAgent">The user agent of the client, if applicable (nullable).</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="columnName"/> is null or whitespace (Spanish message: "El nombre de la columna es requerido.").
        /// Thrown if <paramref name="action"/> is null or whitespace (Spanish message: "La acción es requerida.").
        /// </exception>
        public AuditDeviceEntity(
            int idAuditDevice,
            string columnName,
            int recordId,
            int cropId,
            string action,
            string? oldValue,
            string? newValue,
            DateTime? performedAt,
            int? performedBy,
            string? performedByIp,
            string? userAgent)
        {
            // Validates that required string arguments are provided.
            if (string.IsNullOrWhiteSpace(columnName))
                // Throws exception with the original Spanish message.
                throw new ArgumentException("El nombre de la columna es requerido.", nameof(columnName));
            if (string.IsNullOrWhiteSpace(action))
                // Throws exception with the original Spanish message.
                throw new ArgumentException("La acción es requerida.", nameof(action));

            // Assigns validated parameters to the corresponding properties.
            IdAuditDevice = idAuditDevice;
            ColumnName = columnName;
            RecordId = recordId;
            CropId = cropId;
            Action = action;
            OldValue = oldValue;
            NewValue = newValue;
            PerformedAt = performedAt;
            PerformedBy = performedBy;
            PerformedByIp = performedByIp;
            UserAgent = userAgent;
        }
    }
}