namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a single audit trail record specifically tracking actions involving access to,
    /// or operations on, sensitive data fields within specified database tables, associated with a crop.
    /// Note: This entity primarily logs the action performed (e.g., access, decryption) rather than the data values themselves.
    /// </summary>
    public class AuditSensitiveDataEntity
    {
        /// <summary>
        /// Gets the unique identifier for this sensitive data audit log entry.
        /// </summary>
        public int IdAuditSensitiveData { get; private set; }

        /// <summary>
        /// Gets the name of the database table containing the sensitive data that was accessed or modified.
        /// </summary>
        public string TableName { get; private set; }

        /// <summary>
        /// Gets the name of the specific column containing the sensitive data involved in the action.
        /// </summary>
        public string ColumnName { get; private set; }

        /// <summary>
        /// Gets the identifier (primary key) of the specific record within the table whose sensitive data was involved.
        /// </summary>
        public int RecordId { get; private set; }

        /// <summary>
        /// Gets the identifier of the crop context relevant to the audited sensitive data action.
        /// </summary>
        public int CropId { get; private set; }

        /// <summary>
        /// Gets the type of action performed on the sensitive data (e.g., "READ_ACCESS", "DECRYPTION_ATTEMPT", "EXPORTED").
        /// </summary>
        public string Action { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the action involving sensitive data was performed. Nullable.
        /// </summary>
        public DateTime? PerformedAt { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the user who performed the action, if available. Nullable.
        /// </summary>
        public int? PerformedBy { get; private set; }

        /// <summary>
        /// Gets the IP address from which the action originated, if available. Nullable.
        /// </summary>
        public string? PerformedByIp { get; private set; }

        /// <summary>
        /// Gets the user agent string of the client that performed the action, if available. Nullable.
        /// </summary>
        public string? UserAgent { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditSensitiveDataEntity"/> class with details about an action on sensitive data.
        /// </summary>
        /// <param name="idAuditSensitiveData">The unique ID for this audit record (often generated by the database).</param>
        /// <param name="tableName">The name of the table containing the sensitive data.</param>
        /// <param name="columnName">The name of the sensitive column involved.</param>
        /// <param name="recordId">The ID of the affected record within the table.</param>
        /// <param name="cropId">The ID of the crop context for this action.</param>
        /// <param name="action">The action performed (e.g., "READ_ACCESS").</param>
        /// <param name="performedAt">The timestamp of the action (nullable).</param>
        /// <param name="performedBy">The ID of the user performing the action (nullable).</param>
        /// <param name="performedByIp">The IP address associated with the action (nullable).</param>
        /// <param name="userAgent">The user agent of the client, if applicable (nullable).</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="tableName"/> is null or whitespace (Spanish message: "El nombre de la tabla es requerido.").
        /// Thrown if <paramref name="columnName"/> is null or whitespace (Spanish message: "El nombre de la columna es requerido.").
        /// Thrown if <paramref name="action"/> is null or whitespace (Spanish message: "La acción es requerida.").
        /// </exception>
        public AuditSensitiveDataEntity(
            int idAuditSensitiveData,
            string tableName,
            string columnName,
            int recordId,
            int cropId,
            string action,
            DateTime? performedAt,
            int? performedBy,
            string? performedByIp,
            string? userAgent)
        {
            // Validates that required string arguments are provided.
            if (string.IsNullOrWhiteSpace(tableName))
            {
                throw new ArgumentException("The table name is required.", nameof(tableName));
            }
            if (string.IsNullOrWhiteSpace(columnName))
            {
                throw new ArgumentException("The column name is required.", nameof(columnName));
            }
            if (string.IsNullOrWhiteSpace(action))
            {
                throw new ArgumentException("The action is required.", nameof(action));
            }

            // Assigns validated parameters to the corresponding properties.
            IdAuditSensitiveData = idAuditSensitiveData;
            TableName = tableName;
            ColumnName = columnName;
            RecordId = recordId;
            CropId = cropId;
            Action = action;
            PerformedAt = performedAt;
            PerformedBy = performedBy;
            PerformedByIp = performedByIp;
            UserAgent = userAgent;
        }
    }
}