namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a record containing a temporary token generated to allow a user
    /// to securely reset their password.
    /// </summary>
    public class ChangePasswordEntity
    {
        /// <summary>
        /// Gets the unique identifier for this password change request record.
        /// </summary>
        public int IdChangePassword { get; private set; }

        /// <summary>
        /// Gets the secure, unique token string sent to the user for password reset verification.
        /// </summary>
        public string PasswordResetToken { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when this password reset token expires and becomes invalid.
        /// </summary>
        public DateTime ResetTokenExpiresAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when this password reset token was originally created.
        /// </summary>
        public DateTime TokenCreatedAt { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the person (user) to whom this password reset token belongs.
        /// </summary>
        public int? PersonId { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChangePasswordEntity"/> class with specific token details.
        /// </summary>
        /// <param name="idChangePassword">The unique ID for this record (often generated by the database).</param>
        /// <param name="passwordResetToken">The secure token string.</param>
        /// <param name="resetTokenExpiresAt">The expiration timestamp for the token.</param>
        /// <param name="tokenCreatedAt">The creation timestamp for the token.</param>
        /// <param name="personId">The ID of the user associated with this token.</param>
        public ChangePasswordEntity(
            int idChangePassword,
            string passwordResetToken,
            DateTime resetTokenExpiresAt,
            DateTime tokenCreatedAt,
            int? personId)
        {
            // Direct assignment of parameters to properties. No validation logic present in this constructor.
            IdChangePassword = idChangePassword;
            PasswordResetToken = passwordResetToken;
            ResetTokenExpiresAt = resetTokenExpiresAt;
            TokenCreatedAt = tokenCreatedAt;
            PersonId = personId;
        }
    }
}