namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents an invitation code record used to grant access
    /// or link a new user to a specific crop.
    /// </summary>
    public class CropInvitationEntity
    {
        /// <summary>
        /// Gets the unique identifier for this crop invitation record.
        /// </summary>
        public int IdCropInvitation { get; private set; }

        /// <summary>
        /// Gets the unique access code string associated with this invitation.
        /// Note: The property name contains the typo 'Acces'.
        /// </summary>
        public string AccessCode { get; private set; } 

        /// <summary>
        /// Gets the date and time (usually UTC) when this invitation code was created.
        /// </summary>
        public DateTime CreatedAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when this invitation code expires and becomes invalid.
        /// </summary>
        public DateTime ExpiresAt { get; private set; }

        /// <summary>
        /// Gets the identifier representing the current status of the invitation (e.g., Pending, Used, Expired). Nullable.
        /// </summary>
        public int? StatusId { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the user who created this invitation. Nullable.
        /// </summary>
        public int? CreatedBy { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the user who used or accepted this invitation. Nullable if unused.
        /// </summary>
        public int? UsedBy { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the crop to which this invitation grants access.
        /// </summary>
        public int CropId { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="CropInvitationEntity"/> class.
        /// </summary>
        /// <param name="idCropInvitation">The unique ID for this invitation record (often generated by the database).</param>
        /// <param name="accessCode">The unique access code string.</param>
        /// <param name="createdAt">The creation timestamp.</param>
        /// <param name="expiresAt">The expiration timestamp.</param>
        /// <param name="statusId">The initial status ID (nullable).</param>
        /// <param name="createdBy">The ID of the user creating the invitation (nullable).</param>
        /// <param name="usedBy">The ID of the user who used the invitation (nullable).</param>
        /// <param name="cropId">The ID of the crop this invitation relates to.</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="accessCode"/> is null or whitespace (Spanish message: "El código de acceso es requerido.").
        /// </exception>
        public CropInvitationEntity(
            int idCropInvitation,
            string accessCode, 
            DateTime createdAt,
            DateTime expiresAt,
            int? statusId,
            int? createdBy,
            int? usedBy,
            int cropId)
        {
            // Validates that the access code is provided.
            if (string.IsNullOrWhiteSpace(accessCode))
                throw new ArgumentException("El código de acceso es requerido.", nameof(accessCode));

            IdCropInvitation = idCropInvitation;
            AccessCode = accessCode; 
            CreatedAt = createdAt;
            ExpiresAt = expiresAt;
            StatusId = statusId;
            CreatedBy = createdBy;
            UsedBy = usedBy;
            CropId = cropId;
        }
    }
}