namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents an agricultural crop entity, containing its identification,
    /// name, location, and administrative details.
    /// </summary>
    public class CropEntity
    {
        /// <summary>
        /// Gets the unique identifier for the crop.
        /// </summary>
        public int IdCrop { get; private set; }

        /// <summary>
        /// Gets the name assigned to the crop.
        /// </summary>
        public string NameCrop { get; private set; }

        /// <summary>
        /// Gets the physical address associated with the crop's location.
        /// Note: The property name contains the typo 'Addres'.
        /// </summary>
        public string AddressCrop { get; private set; } 

        /// <summary>
        /// Gets the name of the city where the crop is located.
        /// </summary>
        public string CityName { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the crop entity was created.
        /// </summary>
        public DateTime CreatedAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the crop entity was last updated. Nullable if never updated.
        /// </summary>
        public DateTime? UpdatedAt { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the administrator user primarily associated with this crop. Nullable.
        /// </summary>
        public int? AdminUserId { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="CropEntity"/> class.
        /// </summary>
        /// <param name="idCrop">The unique ID for the crop (often generated by the database).</param>
        /// <param name="nameCrop">The name of the crop.</param>
        /// <param name="addressCrop">The physical address of the crop.</param>
        /// <param name="cityName">The city where the crop is located.</param>
        /// <param name="createdAt">The creation timestamp.</param>
        /// <param name="adminUserId">The ID of the administrator user associated with the crop (optional, defaults to null).</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="nameCrop"/> is null or whitespace (Spanish message: "El nombre del cultivo es requerido.").
        /// Thrown if <paramref name="addressCrop"/> is null or whitespace (Spanish message: "La dirección es requerida.").
        /// Thrown if <paramref name="cityName"/> is null or whitespace (Spanish message: "El nombre de la ciudad es requerido.").
        /// </exception>
        public CropEntity(
            int idCrop,
            string nameCrop,
            string addressCrop, 
            string cityName,
            DateTime createdAt,
            int? adminUserId = null)
        {
            // Validates required string fields.
            if (string.IsNullOrWhiteSpace(nameCrop))
                throw new ArgumentException("El nombre del cultivo es requerido.", nameof(nameCrop));
            if (string.IsNullOrWhiteSpace(addressCrop))
                throw new ArgumentException("La dirección es requerida.", nameof(addressCrop));
            if (string.IsNullOrWhiteSpace(cityName))
                throw new ArgumentException("El nombre de la ciudad es requerido.", nameof(cityName));

            IdCrop = idCrop;
            NameCrop = nameCrop;
            AddressCrop = addressCrop; 
            CityName = cityName;
            CreatedAt = createdAt;
            AdminUserId = adminUserId;
        }
    }
}