namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a pair of authentication tokens (access and refresh) issued specifically for a device,
    /// along with metadata about the token's lifecycle and the device context.
    /// </summary>
    public class DeviceTokenEntity
    {
        /// <summary>
        /// Gets the unique identifier for this device token record.
        /// </summary>
        public int IdDeviceToken { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the device associated with these tokens. Nullable if not directly linked.
        /// </summary>
        public int? DeviceId { get; private set; }

        /// <summary>
        /// Gets the access token string (e.g., JWT) used for short-term authentication.
        /// </summary>
        public string Token { get; private set; }

        /// <summary>
        /// Gets the refresh token string used to obtain new access tokens.
        /// </summary>
        public string RefreshToken { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when these tokens were created.
        /// </summary>
        public DateTime CreatedAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the refresh token expires.
        /// </summary>
        public DateTime ExpiresAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the refresh token was revoked. Nullable if still active.
        /// </summary>
        public DateTime? RevokedAt { get; private set; }

        /// <summary>
        /// Gets the IP address from which the revocation request originated, if applicable.
        /// </summary>
        public string RevokedByIp { get; private set; } // Consider making nullable if not always available on revoke? Original code assumes non-null.

        /// <summary>
        /// Gets descriptive information about the device associated with these tokens at the time of issuance or refresh.
        /// </summary>
        public string DeviceInfo { get; private set; }

        /// <summary>
        /// Gets the user agent string of the client associated with these tokens at the time of issuance or refresh.
        /// </summary>
        public string UserAgent { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceTokenEntity"/> class.
        /// </summary>
        /// <param name="idDeviceToken">The unique ID for this token record (often generated by the database).</param>
        /// <param name="deviceId">The ID of the associated device (nullable).</param>
        /// <param name="token">The access token string.</param>
        /// <param name="refreshToken">The refresh token string.</param>
        /// <param name="createdAt">The creation timestamp.</param>
        /// <param name="expiresAt">The expiration timestamp for the refresh token.</param>
        /// <param name="revokedAt">The revocation timestamp (nullable if active).</param>
        /// <param name="revokedByIp">The IP address causing revocation (if applicable).</param>
        /// <param name="deviceInfo">Information about the associated device.</param>
        /// <param name="userAgent">The user agent string of the client.</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="token"/> is null or whitespace (Spanish message: "El token es requerido.").
        /// Thrown if <paramref name="refreshToken"/> is null or whitespace (Spanish message: "El refresh token es requerido.").
        /// </exception>
        public DeviceTokenEntity(
            int idDeviceToken,
            int? deviceId,
            string token,
            string refreshToken,
            DateTime createdAt,
            DateTime expiresAt,
            DateTime? revokedAt,
            string revokedByIp, 
            string deviceInfo,
            string userAgent)
        {
            // Validates that required token strings are provided.
            if (string.IsNullOrWhiteSpace(token))
                throw new ArgumentException("El token es requerido.", nameof(token));
            if (string.IsNullOrWhiteSpace(refreshToken))
                throw new ArgumentException("El refresh token es requerido.", nameof(refreshToken));

            // Assigns validated parameters to the corresponding properties.
            IdDeviceToken = idDeviceToken;
            DeviceId = deviceId;
            Token = token;
            RefreshToken = refreshToken;
            CreatedAt = createdAt;
            ExpiresAt = expiresAt;
            RevokedAt = revokedAt;
            RevokedByIp = revokedByIp;
            DeviceInfo = deviceInfo;
            UserAgent = userAgent;
        }
    }
}