namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a record containing an activation code used to register,
    /// authorize, or link a physical device to the system.
    /// </summary>
    public class DeviceActivationEntity
    {
        /// <summary>
        /// Gets the unique identifier for this device activation record.
        /// </summary>
        public int IdDeviceActivation { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the device associated with this activation code,
        /// once activated. Nullable if the code is pending activation or not linked yet.
        /// </summary>
        public int? DeviceId { get; private set; }

        /// <summary>
        /// Gets the unique code required to activate the device.
        /// </summary>
        public string ActivationCode { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when this activation code was created.
        /// </summary>
        public DateTime CreatedAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when this activation code expires and becomes invalid.
        /// </summary>
        public DateTime ExpiresAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the device was successfully activated using this code.
        /// Nullable if the code has not been used yet.
        /// </summary>
        public DateTime? ActivatedAt { get; set; }

        /// <summary>
        /// Gets the identifier representing the current status of the activation code
        /// (e.g., Pending, Active, Expired, Used). Nullable.
        /// </summary>
        public int? ActivationStatus { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceActivationEntity"/> class,
        /// typically used when generating a new activation code.
        /// </summary>
        /// <param name="idDeviceActivation">The unique ID for this record (often generated by the database).</param>
        /// <param name="deviceId">The ID of the device this code might be linked to (nullable initially).</param>
        /// <param name="activationCode">The activation code string.</param>
        /// <param name="createdAt">The creation timestamp.</param>
        /// <param name="expiresAt">The expiration timestamp.</param>
        /// <param name="activationStatus">The initial activation status ID (optional, defaults to null).</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="activationCode"/> is null.</exception>
        /// <remarks>
        /// Note that the <see cref="ActivatedAt"/> property is not set by this constructor and remains null initially.
        /// </remarks>
        public DeviceActivationEntity(
            int idDeviceActivation,
            int? deviceId,
            string activationCode,
            DateTime createdAt,
            DateTime expiresAt,
            int? activationStatus = null)
        {
            IdDeviceActivation = idDeviceActivation;
            DeviceId = deviceId;
            ActivationCode = activationCode ?? throw new ArgumentNullException(nameof(activationCode));
            CreatedAt = createdAt;
            ExpiresAt = expiresAt;
            ActivationStatus = activationStatus;
        }
    }
}