namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a single log entry generated by, or related to, a specific device.
    /// Used for recording events, errors, or informational messages from devices.
    /// </summary>
    public class DeviceLogEntity
    {
        /// <summary>
        /// Gets the unique identifier for this device log record.
        /// </summary>
        public int IdDeviceLog { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the device that generated or is related to this log entry.
        /// </summary>
        public int DeviceId { get; private set; }

        /// <summary>
        /// Gets the type or category of the log entry (e.g., "INFO", "WARNING", "ERROR", "CONNECTION").
        /// </summary>
        public string LogType { get; private set; }

        /// <summary>
        /// Gets the detailed message content of the log entry.
        /// </summary>
        public string LogMessage { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the event logged occurred or was recorded.
        /// </summary>
        public DateTime LogTimestamp { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceLogEntity"/> class.
        /// </summary>
        /// <param name="idDeviceLog">The unique ID for this log record (often generated by the database).</param>
        /// <param name="deviceId">The ID of the related device.</param>
        /// <param name="logType">The type or category of the log.</param>
        /// <param name="logMessage">The message content of the log.</param>
        /// <param name="logTimestamp">The timestamp when the logged event occurred.</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="logType"/> is null or whitespace (Spanish message: "El tipo de log es requerido.").
        /// Thrown if <paramref name="logMessage"/> is null or whitespace (Spanish message: "El mensaje de log es requerido.").
        /// </exception>
        public DeviceLogEntity(
            int idDeviceLog,
            int deviceId,
            string logType,
            string logMessage,
            DateTime logTimestamp)
        {
            // Validates that required string fields are provided.
            if (string.IsNullOrWhiteSpace(logType))
            {
                throw new ArgumentException("The log type is required.", nameof(logType));
            }
            if (string.IsNullOrWhiteSpace(logMessage))
            {
                throw new ArgumentException("The log message is required.", nameof(logMessage));
            }

            // Assigns validated parameters to the corresponding properties.
            IdDeviceLog = idDeviceLog;
            DeviceId = deviceId;
            LogType = logType;
            LogMessage = logMessage;
            LogTimestamp = logTimestamp;
        }
    }
}