namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a data-collecting device, containing its identification, description,
    /// configuration settings, registration details, and associations (crop, plant).
    /// </summary>
    public class DeviceDataEntity
    {
        /// <summary>
        /// Gets the unique identifier for the device data record.
        /// </summary>
        public int IdDeviceData { get; private set; }

        /// <summary>
        /// Gets the name assigned to the device.
        /// </summary>
        public string NameDevice { get; private set; }

        /// <summary>
        /// Gets a description of the device.
        /// </summary>
        public string DescriptionDevice { get; private set; }

        /// <summary>
        /// Gets the configured time interval for data collection (e.g., in minutes or seconds).
        /// </summary>
        public short DataCollectionTime { get; private set; }

        /// <summary>
        /// Gets the identifier representing the current status of the device (e.g., Active, Inactive, Error). Nullable.
        /// </summary>
        public int? StatusId { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the device was registered in the system.
        /// </summary>
        public DateTime RegisteredAt { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the user who registered the device. Nullable.
        /// </summary>
        public int? RegisteredBy { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the device entity was last updated. Nullable if never updated.
        /// </summary>
        public DateTime? UpdatedAt { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the user who last updated the device entity. Nullable if never updated.
        /// </summary>
        public int? UpdatedBy { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the crop to which this device is assigned. Nullable.
        /// </summary>
        public int? CropId { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the specific plant this device is monitoring, if applicable. Nullable.
        /// </summary>
        public int? PlantId { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceDataEntity"/> class, typically upon device registration.
        /// </summary>
        /// <param name="idDeviceData">The unique ID for this device record (often generated by the database).</param>
        /// <param name="nameDevice">The name of the device.</param>
        /// <param name="descriptionDevice">The description of the device.</param>
        /// <param name="dataCollectionTime">The data collection interval.</param>
        /// <param name="registeredAt">The registration timestamp.</param>
        /// <param name="registeredBy">The ID of the user registering the device (nullable).</param>
        /// <param name="statusId">The initial status ID (nullable).</param>
        /// <param name="cropId">The ID of the crop the device is assigned to (nullable).</param>
        /// <param name="plantId">The ID of the plant the device is assigned to (nullable).</param>
        /// <exception cref="ArgumentOutOfRangeException">Thrown if <paramref name="dataCollectionTime"/> is negative
        /// (Spanish message: "El tiempo de recolección no puede ser negativo.").</exception>
        /// <remarks>
        /// Note that <see cref="UpdatedAt"/> and <see cref="UpdatedBy"/> properties are not set by this constructor
        /// and remain null initially.
        /// </remarks>
        public DeviceDataEntity(
            int idDeviceData,
            string nameDevice,
            string descriptionDevice,
            short dataCollectionTime,
            DateTime registeredAt,
            int? registeredBy,
            int? statusId,
            int? cropId,
            int? plantId)
        {
            // Validates that the data collection time is not negative.
            if (dataCollectionTime < 0){
                throw new ArgumentOutOfRangeException(nameof(dataCollectionTime), "Collection time cannot be negative.");
            }

            // Assigns parameters to the corresponding properties.
            IdDeviceData = idDeviceData;
            NameDevice = nameDevice;
            DescriptionDevice = descriptionDevice;
            DataCollectionTime = dataCollectionTime;
            RegisteredAt = registeredAt;
            RegisteredBy = registeredBy;
            StatusId = statusId;
            CropId = cropId;
            PlantId = plantId;
        }
    }
}