namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a record logging a single failed login attempt against a specific user account.
    /// Used for security monitoring and potentially implementing lockout mechanisms.
    /// </summary>
    public class FailedLoginAttemptEntity
    {
        /// <summary>
        /// Gets the unique identifier for this failed login attempt record.
        /// </summary>
        public int IdFailedLoginAttempt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the failed login attempt occurred.
        /// </summary>
        public DateTime AttemptDate { get; private set; }

        /// <summary>
        /// Gets the IP address from which the failed login attempt originated.
        /// </summary>
        public string IpAddress { get; private set; }

        /// <summary>
        /// Gets descriptive information about the device used for the failed login attempt.
        /// </summary>
        public string DeviceInfo { get; private set; }

        /// <summary>
        /// Gets the user agent string of the client used for the failed login attempt.
        /// </summary>
        public string UserAgent { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the person (user) account that was targeted by the failed login attempt.
        /// </summary>
        public int PersonId { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="FailedLoginAttemptEntity"/> class.
        /// </summary>
        /// <param name="idFailedLoginAttempt">The unique ID for this record (often generated by the database).</param>
        /// <param name="attemptDate">The timestamp of the failed attempt.</param>
        /// <param name="ipAddress">The source IP address.</param>
        /// <param name="deviceInfo">Information about the device used.</param>
        /// <param name="userAgent">The user agent string of the client.</param>
        /// <param name="personId">The ID of the user account targeted.</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="ipAddress"/> is null or whitespace (Spanish message: "La dirección IP es requerida.").
        /// Thrown if <paramref name="deviceInfo"/> is null or whitespace (Spanish message: "La información del dispositivo es requerida.").
        /// Thrown if <paramref name="userAgent"/> is null or whitespace (Spanish message: "El user agent es requerido.").
        /// </exception>
        public FailedLoginAttemptEntity(
            int idFailedLoginAttempt,
            DateTime attemptDate,
            string ipAddress,
            string deviceInfo,
            string userAgent,
            int personId)
        {
            // Validates that required string fields identifying the attempt context are provided.
            if (string.IsNullOrWhiteSpace(ipAddress))
                throw new ArgumentException("La dirección IP es requerida.", nameof(ipAddress));
            if (string.IsNullOrWhiteSpace(deviceInfo))
                throw new ArgumentException("La información del dispositivo es requerida.", nameof(deviceInfo));
            if (string.IsNullOrWhiteSpace(userAgent))
                throw new ArgumentException("El user agent es requerido.", nameof(userAgent));

            // Assigns validated parameters to the corresponding properties.
            IdFailedLoginAttempt = idFailedLoginAttempt;
            AttemptDate = attemptDate;
            IpAddress = ipAddress;
            DeviceInfo = deviceInfo;
            UserAgent = userAgent;
            PersonId = personId;
        }
    }
}