namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a user account in the system, containing personal details, credentials (typically hashed password),
    /// status flags, timestamps, and associations like the assigned crop.
    /// </summary>
    public class PersonEntity
    {
        /// <summary>
        /// Gets the unique identifier for the person (user).
        /// </summary>
        public int IdPerson { get; private set; }

        /// <summary>
        /// Gets the user's first name.
        /// </summary>
        public string FirstName { get; private set; }

        /// <summary>
        /// Gets the user's last name.
        /// </summary>
        public string LastName { get; private set; }

        /// <summary>
        /// Gets the user's email address, typically used for login.
        /// </summary>
        public string Email { get; private set; }

        /// <summary>
        /// Gets the user's password hash. Direct access returns the stored hash, not the plain text password.
        /// </summary>
        public string Password { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the user account was created.
        /// </summary>
        public DateTime CreatedAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the user account details were last updated. Nullable if never updated.
        /// </summary>
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Gets the date and time (usually UTC) of the user's last successful login. Nullable if never logged in.
        /// </summary>
        public DateTime? LastLoginAt { get; set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the user's password was last changed. Nullable if never changed after creation.
        /// </summary>
        public DateTime? LastPasswordChangeAt { get; set; }

        /// <summary>
        /// Gets a value indicating whether the user has administrative privileges.
        /// </summary>
        public bool IsAdmin { get; private set; }

        /// <summary>
        /// Gets a value indicating whether the user wishes to receive all types of notifications.
        /// </summary>
        public bool AllNotifications { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the crop this user is associated with. Nullable if not associated with a specific crop.
        /// </summary>
        public int? CropId { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PersonEntity"/> class, typically upon user creation.
        /// </summary>
        /// <param name="idPerson">The unique ID for the person (often generated by the database).</param>
        /// <param name="firstName">The user's first name.</param>
        /// <param name="lastName">The user's last name.</param>
        /// <param name="email">The user's email address.</param>
        /// <param name="password">The user's password (typically the hashed password).</param>
        /// <param name="createdAt">The creation timestamp.</param>
        /// <param name="isAdmin">Flag indicating if the user is an administrator.</param>
        /// <param name="allNotifications">Flag indicating notification preference.</param>
        /// <param name="cropId">The ID of the crop the user is associated with (optional, defaults to null).</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="firstName"/> is null or whitespace (Spanish message: "El nombre es requerido.").
        /// Thrown if <paramref name="lastName"/> is null or whitespace (Spanish message: "El apellido es requerido.").
        /// </exception>
        /// <remarks>
        /// Note that <see cref="UpdatedAt"/>, <see cref="LastLoginAt"/>, and <see cref="LastPasswordChangeAt"/> properties
        /// are not set by this constructor and remain null initially.
        /// </remarks>
        public PersonEntity(
            int idPerson,
            string firstName,
            string lastName,
            string email,
            string password,
            DateTime createdAt,
            bool isAdmin,
            bool allNotifications,
            int? cropId = null)
        {
            // Validates required name fields.
            if (string.IsNullOrWhiteSpace(firstName))
            {
                throw new ArgumentException("First name is required.", nameof(firstName));
            }
            if (string.IsNullOrWhiteSpace(lastName))
            {
                throw new ArgumentException("Last name is required.", nameof(lastName));
            }

            // Assigns validated parameters to the corresponding properties.
            IdPerson = idPerson;
            FirstName = firstName;
            LastName = lastName;
            Email = email;
            Password = password; 
            CreatedAt = createdAt;
            IsAdmin = isAdmin;
            AllNotifications = allNotifications;
            CropId = cropId;
        }
    }
}