namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents an individual plant within a crop, containing its identification,
    /// name, status, registration details, and association with a crop.
    /// </summary>
    public class PlantDataEntity
    {
        /// <summary>
        /// Gets the unique identifier for the plant record (property name is IdPlantState).
        /// </summary>
        public int IdPlantState { get; private set; } // Original property name kept.

        /// <summary>
        /// Gets the name or identifier assigned to the plant.
        /// </summary>
        public string NamePlant { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the plant record was created or registered.
        /// </summary>
        public DateTime RegisteredAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the plant record was last updated. Nullable if never updated.
        /// </summary>
        public DateTime? UpdatedAt { get; private set; }

        /// <summary>
        /// Gets the identifier representing the current status of the plant (e.g., Healthy, Diseased, Harvested). Nullable.
        /// </summary>
        public int? StatusId { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the crop to which this plant belongs. Nullable.
        /// </summary>
        public int? CropId { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlantDataEntity"/> class, typically upon plant creation.
        /// </summary>
        /// <param name="idPlantState">The unique ID for this plant record (often generated by the database).</param>
        /// <param name="namePlant">The name or identifier of the plant.</param>
        /// <param name="registeredAt">The registration timestamp.</param>
        /// <param name="statusId">The initial status ID (nullable).</param>
        /// <param name="cropId">The ID of the crop this plant belongs to (nullable).</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="namePlant"/> is null or whitespace (Spanish message: "El nombre de la planta es requerido.").
        /// </exception>
        /// <remarks>
        /// Note that the <see cref="UpdatedAt"/> property is not set by this constructor and remains null initially.
        /// </remarks>
        public PlantDataEntity(
            int idPlantState,
            string namePlant,
            DateTime registeredAt,
            int? statusId,
            int? cropId)
        {
            // Validates that the plant name is provided.
            if (string.IsNullOrWhiteSpace(namePlant))
            {
                throw new ArgumentException("The plant name is required.", nameof(namePlant));
            }

            // Assigns validated parameters to the corresponding properties.
            IdPlantState = idPlantState;
            NamePlant = namePlant;
            RegisteredAt = registeredAt;
            StatusId = statusId;
            CropId = cropId;
        }
    }
}