namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a historical record documenting a change in a plant's status
    /// at a specific point in time, including who made the change.
    /// </summary>
    public class PlantStateHistoryEntity
    {
        /// <summary>
        /// Gets the unique identifier for this plant state history record.
        /// </summary>
        public int IdPlantStateHistory { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the plant's status was changed.
        /// </summary>
        public DateTime ChangedAt { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the user who made the status change. Nullable if changed by the system or unknown.
        /// </summary>
        public int? ChangedBy { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the plant whose status was changed.
        /// </summary>
        public int PlantId { get; private set; }

        /// <summary>
        /// Gets the identifier representing the status that was assigned to the plant at this point in time. Nullable.
        /// </summary>
        public int? StatusId { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PlantStateHistoryEntity"/> class.
        /// </summary>
        /// <param name="idPlantStateHistory">The unique ID for this history record (often generated by the database).</param>
        /// <param name="changedAt">The timestamp when the status change occurred.</param>
        /// <param name="plantId">The ID of the plant whose status changed.</param>
        /// <param name="statusId">The ID of the status assigned at this time (nullable).</param>
        /// <param name="changedBy">The ID of the user who made the change (optional, defaults to null).</param>
        public PlantStateHistoryEntity(
            int idPlantStateHistory,
            DateTime changedAt,
            int plantId,
            int? statusId,
            int? changedBy = null)
        {
            // Assigns parameters to the corresponding properties. 
            IdPlantStateHistory = idPlantStateHistory;
            ChangedAt = changedAt;
            PlantId = plantId;
            StatusId = statusId;
            ChangedBy = changedBy;
        }
    }
}