namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a refresh token used to obtain new access tokens, extending user sessions.
    /// Contains information about the token itself, its lifecycle (creation, expiration, revocation),
    /// the associated user session, and the context (IP, device) in which it was issued.
    /// </summary>
    public class RefreshTokenEntity
    {
        /// <summary>
        /// Gets the unique identifier for this refresh token record.
        /// </summary>
        public int IdRefreshToken { get; private set; }

        /// <summary>
        /// Gets an identifier grouping tokens belonging to the same logical session or user login instance.
        /// </summary>
        public long Session { get; private set; } 

        /// <summary>
        /// Gets the unique, cryptographically secure refresh token string.
        /// </summary>
        public string Token { get; private set; }

        /// <summary>
        /// Gets descriptive information about the device associated with this token at the time of issuance.
        /// </summary>
        public string DeviceInfo { get; private set; }

        /// <summary>
        /// Gets the IP address from which the token was originally requested.
        /// </summary>
        public string IpAddress { get; private set; }

        /// <summary>
        /// Gets the user agent string of the client from which the token was originally requested.
        /// </summary>
        public string UserAgent { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when this refresh token was created.
        /// </summary>
        public DateTime CreatedAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when this refresh token expires and is no longer valid for obtaining new access tokens.
        /// </summary>
        public DateTime ExpiresAt { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when this refresh token was revoked. Nullable if the token is still active.
        /// </summary>
        public DateTime? RevokedAt { get; private set; }

        /// <summary>
        /// Gets the IP address that initiated the revocation action, if applicable. Nullable if not revoked or IP not recorded.
        /// </summary>
        public string? RevokedByIp { get; private set; }

        /// <summary>
        /// Gets the value (or reference) of the new refresh token that replaced this one, used in token rotation strategies. Nullable if not replaced.
        /// </summary>
        public string? ReplacedByToken { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the person (user) to whom this refresh token belongs. Nullable if associated differently (e.g., device token).
        /// </summary>
        public int? PersonId { get; private set; }

        /// <summary>
        /// Marks the refresh token as revoked.
        /// </summary>
        /// <param name="revokedAt">The UTC timestamp when the token revocation occurred.</param>
        /// <param name="revokedByIp">The IP address associated with the revocation action (can be null).</param>
        public void Revoke(DateTime revokedAt, string? revokedByIp) 
        {
            RevokedAt = revokedAt;
            RevokedByIp = revokedByIp;
        }

        /// <summary>
        /// Marks this refresh token as having been replaced by a new token, part of a rotation strategy.
        /// </summary>
        /// <param name="replacedByToken">The value (or reference) of the new token that replaces this one.</param>
        public void Replace(string replacedByToken)
        {
            ReplacedByToken = replacedByToken;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RefreshTokenEntity"/> class.
        /// </summary>
        /// <param name="idRefreshToken">The unique ID for this token record (often generated by the database).</param>
        /// <param name="session">The session identifier associated with this token.</param>
        /// <param name="token">The refresh token string.</param>
        /// <param name="deviceInfo">Information about the device requesting the token.</param>
        /// <param name="ipAddress">The IP address of the client requesting the token.</param>
        /// <param name="userAgent">The user agent string of the client.</param>
        /// <param name="createdAt">The creation timestamp.</param>
        /// <param name="expiresAt">The expiration timestamp.</param>
        /// <param name="revokedAt">The revocation timestamp (nullable if active).</param>
        /// <param name="revokedByIp">The IP address causing revocation (nullable).</param>
        /// <param name="replacedByToken">The token that replaces this one (nullable).</param>
        /// <param name="personId">The ID of the user associated with this token (nullable).</param>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="token"/> is null or whitespace (Spanish message: "El token es requerido.").
        /// Thrown if <paramref name="deviceInfo"/> is null or whitespace (Spanish message: "La información del dispositivo es requerida.").
        /// Thrown if <paramref name="ipAddress"/> is null or whitespace (Spanish message: "La dirección IP es requerida.").
        /// Thrown if <paramref name="userAgent"/> is null or whitespace (Spanish message: "El user agent es requerido.").
        /// </exception>
        public RefreshTokenEntity(
            int idRefreshToken,
            long session,
            string token,
            string deviceInfo,
            string ipAddress,
            string userAgent,
            DateTime createdAt,
            DateTime expiresAt,
            DateTime? revokedAt,
            string? revokedByIp, 
            string? replacedByToken, 
            int? personId)
        {
            // Validates required context fields.
            if (string.IsNullOrWhiteSpace(token))
                throw new ArgumentException("El token es requerido.", nameof(token));
            if (string.IsNullOrWhiteSpace(deviceInfo))
                throw new ArgumentException("La información del dispositivo es requerida.", nameof(deviceInfo));
            if (string.IsNullOrWhiteSpace(ipAddress))
                throw new ArgumentException("La dirección IP es requerida.", nameof(ipAddress));
            if (string.IsNullOrWhiteSpace(userAgent))
                throw new ArgumentException("El user agent es requerido.", nameof(userAgent));

            // Assigns validated parameters to the corresponding properties.
            IdRefreshToken = idRefreshToken;
            Session = session;
            Token = token;
            DeviceInfo = deviceInfo;
            IpAddress = ipAddress;
            UserAgent = userAgent;
            CreatedAt = createdAt;
            ExpiresAt = expiresAt;
            RevokedAt = revokedAt;
            RevokedByIp = revokedByIp;
            ReplacedByToken = replacedByToken;
            PersonId = personId;
        }
    }
}