namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a single snapshot of environmental sensor readings (temperature, humidity, light intensity)
    /// recorded at a specific time. May include external weather context and be associated with a plant or crop.
    /// </summary>
    public class SensorDataEntity
    {
        /// <summary>
        /// Gets the unique identifier for this sensor data record.
        /// </summary>
        public int IdSensorData { get; private set; }

        /// <summary>
        /// Gets the temperature reading (units depend on sensor configuration, e.g., Celsius).
        /// </summary>
        public double Temperature { get; private set; }

        /// <summary>
        /// Gets the relative humidity reading (typically as a percentage, 0-100).
        /// </summary>
        public double Humidity { get; private set; }

        /// <summary>
        /// Gets the light intensity reading (units depend on sensor configuration, e.g., Lux).
        /// </summary>
        public double LightIntensity { get; private set; }

        /// <summary>
        /// Gets the ambient temperature of the city or general area at the time of recording, if available. Nullable.
        /// </summary>
        public double? CityTemperature { get; private set; }

        /// <summary>
        /// Gets the ambient relative humidity of the city or general area at the time of recording, if available. Nullable.
        /// </summary>
        public double? CityHumidity { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when these sensor readings were recorded.
        /// </summary>
        public DateTime RecordedAt { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the plant associated with these sensor readings. Nullable if not linked to a specific plant.
        /// </summary>
        public int? PlantId { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the crop associated with these sensor readings. Nullable if not linked to a specific crop.
        /// </summary>
        public int? CropId { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="SensorDataEntity"/> class.
        /// </summary>
        /// <param name="idSensorData">The unique ID for this sensor data record (often generated by the database).</param>
        /// <param name="temperature">The temperature reading.</param>
        /// <param name="humidity">The humidity reading (expected 0-100).</param>
        /// <param name="lightIntensity">The light intensity reading (expected non-negative).</param>
        /// <param name="cityTemperature">The external city temperature (nullable).</param>
        /// <param name="cityHumidity">The external city humidity (nullable).</param>
        /// <param name="recordedAt">The timestamp when the readings were recorded.</param>
        /// <param name="plantId">The ID of the associated plant (nullable).</param>
        /// <param name="cropId">The ID of the associated crop (nullable).</param>
        /// <exception cref="ArgumentOutOfRangeException">
        /// Thrown if <paramref name="humidity"/> is outside the range [0, 100] (Spanish message: "La humedad debe estar entre 0 y 100.").
        /// Thrown if <paramref name="lightIntensity"/> is negative (Spanish message: "La intensidad de la luz no puede ser negativa.").
        /// </exception>
        public SensorDataEntity(
            int idSensorData,
            double temperature,
            double humidity,
            double lightIntensity,
            double? cityTemperature,
            double? cityHumidity,
            DateTime recordedAt,
            int? plantId,
            int? cropId)
        {
            // Validates sensor reading ranges.
            if (humidity < 0 || humidity > 100)
            {
                throw new ArgumentOutOfRangeException(nameof(humidity), "Humidity must be between 0 and 100.");
            }
            if (lightIntensity < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(lightIntensity), "Light intensity cannot be negative.");
            }

            // Assigns validated parameters to the corresponding properties.
            IdSensorData = idSensorData;
            Temperature = temperature;
            Humidity = humidity;
            LightIntensity = lightIntensity;
            CityTemperature = cityTemperature;
            CityHumidity = cityHumidity;
            RecordedAt = recordedAt;
            PlantId = plantId;
            CropId = cropId;
        }
    }
}