namespace ArandanoIRT_Backend.Domain.Entities
{
    /// <summary>
    /// Represents a single record containing thermal image data and corresponding RGB image data,
    /// captured at a specific time and potentially associated with a plant or crop.
    /// </summary>
    public class ThermalDataEntity
    {
        /// <summary>
        /// Gets the unique identifier for this thermal data record.
        /// </summary>
        public int IdThermalData { get; private set; }

        /// <summary>
        /// Gets the thermal image data, likely stored as a Base64 encoded string, file path, or URI.
        /// </summary>
        public string ThermalImageData { get; private set; }

        /// <summary>
        /// Gets the corresponding RGB (standard color) image data as a read-only list of bytes.
        /// Provides read-only access to prevent external modification of the internal array.
        /// </summary>
        public IReadOnlyList<byte> RgbImageData { get; private set; }

        /// <summary>
        /// Gets the date and time (usually UTC) when the image data was recorded or captured.
        /// </summary>
        public DateTime RecordedAt { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the plant associated with this image data. Nullable if not linked to a specific plant.
        /// </summary>
        public int? PlantId { get; private set; }

        /// <summary>
        /// Gets the unique identifier of the crop associated with this image data. Nullable if not linked to a specific crop.
        /// </summary>
        public int? CropId { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ThermalDataEntity"/> class.
        /// </summary>
        /// <param name="idThermalData">The unique ID for this thermal data record (often generated by the database).</param>
        /// <param name="thermalImageData">The thermal image data (e.g., Base64 string or path).</param>
        /// <param name="rgbImageData">The corresponding RGB image data as a byte array.</param>
        /// <param name="recordedAt">The timestamp when the data was recorded.</param>
        /// <param name="plantId">The ID of the associated plant (nullable).</param>
        /// <param name="cropId">The ID of the associated crop (nullable).</param>
        /// <exception cref="ArgumentNullException">Thrown if <paramref name="rgbImageData"/> is null.</exception>
        /// <exception cref="ArgumentException">Thrown if <paramref name="thermalImageData"/> is null or whitespace.</exception>
        public ThermalDataEntity(
            int idThermalData,
            string thermalImageData,
            byte[] rgbImageData, 
            DateTime recordedAt,
            int? plantId,
            int? cropId)
        {
            // Validates that thermal image data is provided.
            if (string.IsNullOrWhiteSpace(thermalImageData))
                throw new ArgumentException("Thermal image data is required.", nameof(thermalImageData)); 

            ArgumentNullException.ThrowIfNull(rgbImageData, nameof(rgbImageData));

            IdThermalData = idThermalData;
            ThermalImageData = thermalImageData;
            RgbImageData = rgbImageData;
            RecordedAt = recordedAt;
            PlantId = plantId;
            CropId = cropId;
        }
    }
}